#spring.datasource.url=jdbc:postgresql://localhost:5432/car_sales_db
#spring.datasource.username=postgres
#spring.datasource.password=123
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.generate-ddl=true
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.show_sql=true

server:
  port: 8080
spring:
  application:
    name: BackEnd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_sales_db
    username: postgres
    password: 123
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

